default: &default
  adapter: postgresql
  encoding: unicode
  min_messages: WARNING
  pool: 5

development:
  <<: *default
  database: rails_react-development

test:
  <<: *default
  database: rails_react-test

production:
  <<: *default
  database: rails_react-production
